"use client";

import React from "react";
import { QrCode, ShieldCheck, Lock, Clock } from "lucide-react";

interface TeamQRCardProps {
  teamId: string;
  squadCode?: string;
  teamName: string;
  leaderName?: string;
  clearanceLevel?: number;
  isLocked?: boolean;
}

export default function TeamQRCard({
  teamId,
  teamName,
  isLocked = true,
}: TeamQRCardProps) {
  return (
    <div className="vv-card vv-corners" style={{ padding: "1.75rem", display: "flex", flexDirection: "column", gap: "1.25rem" }}>
      {/* Top Telemetry Banner */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid var(--border-blue)", paddingBottom: "0.75rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <ShieldCheck size={16} style={{ color: "var(--cyan)" }} />
          <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.7rem", color: "var(--cyan)", letterSpacing: "2px" }}>
            OFFICIAL TEAM QR PASS
          </span>
        </div>
        <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.6rem", color: "var(--text-muted)", padding: "0.2rem 0.5rem", background: "var(--bg-elevated)", border: "1px solid var(--border-blue)", borderRadius: "4px" }}>
          TEAM ID: {teamId}
        </span>
      </div>

      {/* QR Placeholder Box */}
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "2.5rem 1.5rem", background: "var(--bg-elevated)", border: "2px dashed var(--border-blue)", borderRadius: "6px", textAlign: "center", gap: "1rem" }}>
        <div style={{ width: "64px", height: "64px", borderRadius: "50%", background: "var(--primary-dim)", border: "1px solid var(--primary)", display: "flex", alignItems: "center", justifyContent: "center" }}>
          <QrCode size={32} style={{ color: "var(--primary)" }} />
        </div>

        <div>
          <div style={{ fontFamily: "var(--font-heading)", fontSize: "1.2rem", color: "var(--text-main)", letterSpacing: "1px", marginBottom: "0.25rem" }}>
            TEAM QR CODE
          </div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.75rem", color: "var(--cyan)", letterSpacing: "1px" }}>
            QR CODE WILL APPEAR HERE
          </div>
        </div>

        <p style={{ fontFamily: "var(--font-body)", fontSize: "0.8rem", color: "var(--text-muted)", maxWidth: "320px", margin: 0 }}>
          Your official event access QR pass will be generated by the organization upon final team verification.
        </p>
      </div>

      {/* Footer Info */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: "0.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
          <Clock size={13} style={{ color: "var(--cyan)" }} />
          <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", color: "var(--text-muted)" }}>STATUS: AWAITING EVENT CHECK-IN</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
          <Lock size={13} style={{ color: isLocked ? "var(--cyan)" : "var(--primary)" }} />
          <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", color: "var(--cyan)" }}>{teamName}</span>
        </div>
      </div>
    </div>
  );
}
